"""The try-it-here box on the landing page.

A visitor with no account can ask the stage a question and hold a short
conversation with the answer, until it has cost them 5,000 tokens and they
are asked to sign up.

Deliberately a much smaller thing than `/chat`. No account, no conversation
row, no documents, no retrieval, no web research, no claim parsing, no
verification, no profile - the history is held by the browser and posted
back each turn, and nothing is written to the database at all. That is
partly cost, and partly that a demo which quietly stored strangers'
conversations would be a worse product than one that does not.

What it keeps is the mode. The whole point of the box is that the question
picks the companion, so a guest asking in Decision-making gets Decision
mode's actual instructions - the demo is the product, just without the
apparatus around it.
"""

import json
import logging
import uuid
from collections.abc import AsyncIterator

from fastapi import APIRouter, HTTPException, Request, status
from pydantic import BaseModel, Field
from sse_starlette.sse import EventSourceResponse

from app.core.config import settings
from app.core.rate_limit import check_rate_limit
from app.services.anthropic_client import stream_generation
from app.services.claim_parser import ClaimTagStripper, extract_crux
from app.services.guest_demo import (
    MAX_MESSAGE_CHARS,
    SESSION_BUDGET,
    charge,
    exhausted,
    over_global_budget,
    spent,
    trim_history,
)
from app.services.output_cleanup import clean_output
from app.services.prompt_builder import MODE_INSTRUCTIONS, build_system_instructions
from app.services.token_meter import meter

logger = logging.getLogger("clardentity.guest")

router = APIRouter(prefix="/guest", tags=["guest"])

#: The quick path only. A guest answer is a taste, and the flagship model's
#: deliberation is neither needed for that nor affordable at this price.
_MODEL = settings.anthropic_fast_model


def _address(request: Request) -> str:
    """Who to count this against.

    Behind Render the socket peer is the platform's proxy, so every visitor
    would otherwise share one counter and the first of them would exhaust it
    for everybody. The forwarded header is the real address - and it is
    spoofable, which is exactly why the global ceiling above it exists.
    """
    forwarded = request.headers.get("x-forwarded-for", "")
    if forwarded:
        return forwarded.split(",")[0].strip()
    return request.client.host if request.client else "unknown"


class GuestTurn(BaseModel):
    role: str
    content: str


class GuestRequest(BaseModel):
    #: Generated by the browser and kept in its storage. Rotating it buys
    #: another allowance, which is accepted - see services/guest_demo.py.
    session_id: uuid.UUID
    mode: str
    message: str = Field(min_length=1, max_length=MAX_MESSAGE_CHARS)
    history: list[GuestTurn] = Field(default_factory=list)


@router.get("/budget")
async def guest_budget(request: Request, session_id: uuid.UUID) -> dict:
    """What this visitor has left, for a page that wants to know before asking."""
    used, _ = await spent(str(session_id), _address(request))
    return {"used": used, "budget": SESSION_BUDGET, "remaining": max(0, SESSION_BUDGET - used)}


@router.post("/chat")
async def guest_chat(payload: GuestRequest, request: Request) -> EventSourceResponse:
    address = _address(request)
    session_id = str(payload.session_id)

    # Two different refusals, and they are not the same event. One is "you
    # have had your go, here is the way in"; the other is "this is broken
    # for everyone right now", which must never be dressed up as a sign-up
    # prompt.
    await check_rate_limit(f"guest:{address}", max_requests=30, window_seconds=600)

    if payload.mode not in MODE_INSTRUCTIONS or payload.mode == "rapid":
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_CONTENT, detail="Unknown mode"
        )

    if await over_global_budget():
        logger.warning("guest demo over its daily budget; refusing")
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="The demo is resting. Please try again tomorrow, or sign up.",
        )

    if await exhausted(session_id, address):
        return EventSourceResponse(_limit_reached())

    instructions = build_system_instructions(payload.mode)
    history = trim_history([t.model_dump() for t in payload.history])
    conversation = "\n\n".join(
        f"{'User' if t['role'] == 'user' else 'You'}: {t['content']}" for t in history
    )
    input_text = f"{conversation}\n\nUser: {payload.message}" if conversation else payload.message

    async def stream() -> AsyncIterator[dict]:
        text = ""
        # The answer arrives wrapped in the same <crux> and <claim> markup the
        # app's own pipeline unwraps downstream. The demo has none of that
        # pipeline, so without stripping here the visitor's first impression
        # of the product is angle brackets.
        stripper = ClaimTagStripper()
        with meter() as usage:
            try:
                async for event in stream_generation(
                    instructions=instructions, input_text=input_text, model=_MODEL
                ):
                    if event["type"] == "delta":
                        text += event["text"]
                        visible = stripper.feed(event["text"])
                        if visible:
                            yield {"event": "delta", "data": json.dumps({"text": visible})}
                    elif event["type"] == "done":
                        text = event["full_text"]
            except Exception:  # noqa: BLE001 - the visitor gets a sentence, not a stack
                logger.warning("guest answer failed", exc_info=True)
                yield {
                    "event": "error",
                    "data": json.dumps({"detail": "That didn't come through. Try again?"}),
                }
                return

            used = await charge(session_id, address, usage.total_tokens)

        # The gist leads, then a blank line, then the body. The app gives the
        # gist its own card; here it is simply the first paragraph, which is
        # the same shape without the furniture.
        crux, body = extract_crux(text)
        display = f"{crux}\n\n{body}" if crux else body

        yield {
            "event": "done",
            "data": json.dumps(
                {
                    "text": clean_output(display),
                    "used": used,
                    "budget": SESSION_BUDGET,
                    # The client shows the sign-up wall on this rather than
                    # counting for itself - the number that matters is the
                    # one the server charged.
                    "limit_reached": used >= SESSION_BUDGET,
                }
            ),
        }

    return EventSourceResponse(stream())


async def _limit_reached() -> AsyncIterator[dict]:
    yield {
        "event": "done",
        "data": json.dumps(
            {"text": "", "used": SESSION_BUDGET, "budget": SESSION_BUDGET, "limit_reached": True}
        ),
    }
